Feature/array
ildarnarbek/study pull request #1
Opened 2020-04-18 17:30 UTC by ildarnarbek

2020-04-20 17:09 UTC, artempartos requested changes

2020-04-20 17:09 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        @new_array = []
зачем объявлять новый инстанс переменную?

2020-04-20 17:09 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +          @new_array << (item.positive? ? array.max : item)
нужно самому реализовать max

2020-04-20 17:09 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        while @left < @right - 1
давай попробуем реализовать в рекурсивном стиле

2020-04-25 19:04 UTC, Andrew8xx8 requested changes

2020-04-25 19:04 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        bin_search = proc { |array, query, left, right|
Хорошо бы вместо proc вынести код в отдельный метод

2020-04-27 09:43 UTC, Andrew8xx8 approved these changes

2020-04-27 10:11 UTC, merged