Feature/fp2
ildarnarbek/study pull request #3
Opened 2020-04-28 19:05 UTC by ildarnarbek

2020-04-29 11:38 UTC, Andrew8xx8 requested changes

2020-04-29 11:38 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        my_each { |item| result_array << yield(item) }
Нужно реализовать через reduce

2020-04-29 11:38 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        my_each { |item| result_array << item unless item.nil? }
Нужно реализовать через reduce

2020-04-29 11:38 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        my_each { |item| acc = acc.nil? ? item : yield(acc, item) }
Нужно реализовать используя рекурсивный итератор

2020-04-30 09:43 UTC, ildarnarbek commented on test/exercise/fp2/solution.rb
> +        my_each { |item| acc = acc.nil? ? item : yield(acc, item) }
Есть вопрос, нужно/можно добавить новую функцию как итератор и запускать ее из my_reduce или же  нужно сделать только в рамках my_reduce не добавляя дополнительных функций?

2020-04-30 21:20 UTC, ildarnarbek commented on test/exercise/fp2/solution.rb
> +        my_each { |item| result_array << item unless item.nil? }
через обычный reduce или через my_reduce ?

2020-04-30 21:21 UTC, ildarnarbek commented on test/exercise/fp2/solution.rb
> +        my_each { |item| result_array << yield(item) }
через обычный reduce или через my_reduce ?

2020-05-04 16:52 UTC, Andrew8xx8 approved these changes

2020-05-04 18:01 UTC, merged